-- Add sample blog posts for testing
INSERT INTO blogs (
  id,
  title,
  slug,
  excerpt,
  content,
  featured_image_url,
  category,
  tags,
  author,
  status,
  is_pinned,
  view_count,
  created_at,
  updated_at,
  published_at
) VALUES 
(
  gen_random_uuid(),
  'Understanding Solar Panel Efficiency: What You Need to Know',
  'understanding-solar-panel-efficiency',
  'Learn about solar panel efficiency ratings and how they impact your energy production and savings.',
  '<h2>What is Solar Panel Efficiency?</h2><p>Solar panel efficiency refers to the percentage of sunlight that a solar panel can convert into usable electricity. Most residential solar panels have efficiency ratings between 15% and 22%.</p><h2>Factors Affecting Efficiency</h2><ul><li>Panel technology and materials</li><li>Temperature and weather conditions</li><li>Installation angle and orientation</li><li>Shading and obstructions</li></ul><h2>Why Efficiency Matters</h2><p>Higher efficiency panels can generate more electricity in the same amount of space, making them ideal for homes with limited roof space.</p>',
  'https://images.unsplash.com/photo-1509391366360-2e959784a276?w=800&h=400&fit=crop',
  'Technology',
  ARRAY['efficiency', 'solar panels', 'technology', 'energy production'],
  'PV Mart Team',
  'published',
  true,
  0,
  NOW(),
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'Government Subsidies for Solar Installation in India 2024',
  'government-subsidies-solar-india-2024',
  'Complete guide to available government subsidies and incentives for solar installations.',
  '<h2>Available Subsidies</h2><p>The Indian government offers various subsidies to promote solar energy adoption across residential, commercial, and industrial sectors.</p><h2>Residential Subsidies</h2><ul><li>Up to 40% subsidy for rooftop solar installations</li><li>Net metering benefits</li><li>Tax incentives under Section 80C</li></ul><h2>Commercial Benefits</h2><p>Businesses can avail accelerated depreciation benefits and various state-level incentives for solar installations.</p>',
  'https://images.unsplash.com/photo-1497440001374-f26997328c1b?w=800&h=400&fit=crop',
  'Policy',
  ARRAY['subsidies', 'government', 'policy', 'incentives'],
  'PV Mart Team',
  'published',
  false,
  0,
  NOW(),
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'Maintenance Tips for Your Solar Power System',
  'maintenance-tips-solar-power-system',
  'Essential maintenance practices to keep your solar panels running at peak efficiency.',
  '<h2>Regular Cleaning</h2><p>Dust, dirt, and debris can significantly reduce your solar panel efficiency. Regular cleaning is essential for optimal performance.</p><h2>Inspection Schedule</h2><ul><li>Monthly visual inspections</li><li>Quarterly professional maintenance</li><li>Annual comprehensive system check</li></ul><h2>Common Issues</h2><p>Watch out for loose connections, damaged panels, and inverter issues. Early detection can prevent costly repairs.</p>',
  'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=800&h=400&fit=crop',
  'Maintenance',
  ARRAY['maintenance', 'cleaning', 'inspection', 'efficiency'],
  'PV Mart Team',
  'published',
  false,
  0,
  NOW(),
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'ROI Analysis: How Long Does It Take to Recover Solar Investment?',
  'roi-analysis-solar-investment-recovery',
  'Detailed analysis of return on investment for different types of solar installations.',
  '<h2>Understanding Solar ROI</h2><p>The return on investment for solar panels typically ranges from 5 to 10 years, depending on various factors.</p><h2>Factors Affecting ROI</h2><ul><li>Initial installation cost</li><li>Local electricity rates</li><li>Solar irradiance in your area</li><li>Available incentives and subsidies</li></ul><h2>Calculating Your ROI</h2><p>Use our ROI calculator to estimate your specific payback period based on your location and energy consumption.</p>',
  'https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=800&h=400&fit=crop',
  'Finance',
  ARRAY['ROI', 'investment', 'payback', 'finance'],
  'PV Mart Team',
  'published',
  false,
  0,
  NOW(),
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'Choosing the Right Solar Installer: A Complete Guide',
  'choosing-right-solar-installer-guide',
  'Key factors to consider when selecting a solar installation company for your project.',
  '<h2>Experience and Expertise</h2><p>Look for installers with proven experience in solar installations and proper certifications.</p><h2>What to Check</h2><ul><li>Licenses and certifications</li><li>Customer reviews and references</li><li>Warranty offerings</li><li>After-sales support</li></ul><h2>Getting Multiple Quotes</h2><p>Always get quotes from multiple installers to compare pricing, equipment quality, and service offerings.</p>',
  'https://images.unsplash.com/photo-1466611653911-95081537e5b7?w=800&h=400&fit=crop',
  'Guide',
  ARRAY['installer', 'selection', 'guide', 'tips'],
  'PV Mart Team',
  'published',
  false,
  0,
  NOW(),
  NOW(),
  NOW()
); 