name: Supabase Migrations CI

on:
  push:
    branches:
      - main

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download Latest Supabase CLI
        run: |
          set -e
          # Fetch latest release tag from GitHub API
          LATEST=$(curl --silent "https://api.github.com/repos/supabase/cli/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
          # Download the Linux AMD64 tarball
          curl -L "https://github.com/supabase/cli/releases/download/${LATEST}/supabase-cli-linux-amd64.tar.gz" -o supabase.tar.gz
          # Extract and move to /usr/local/bin
          tar -xzf supabase.tar.gz
          chmod +x supabase
          sudo mv supabase /usr/local/bin/supabase
          supabase --version

      - name: Run Supabase migrations
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
          SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
        run: |
          supabase link --project-ref $SUPABASE_PROJECT_REF --password $SUPABASE_DB_PASSWORD
          supabase db push 